import { isResolvedConfig } from '../config/validate';
import type { ResolvedConfig } from '../config/schema';

export const PROTOCOL_VERSION = 1;

/** [matrix index, travel 0..1023, actuation]. `active` is always transmitted. */
export type FrameKey = readonly [id: number, travel: number, active: 0 | 1];

/**
 * `id` is generated by the overlay and is a deliberate deviation from spec §6,
 * which describes these two without one. Counting the connected overlays is
 * impossible without something to tell them apart, and the spec asks for that
 * count as well.
 */
export type HelloMessage = { v: typeof PROTOCOL_VERSION; t: 'hello'; id: string };
export type BeatMessage = { v: typeof PROTOCOL_VERSION; t: 'beat'; id: string };
/**
 * Sent as the overlay page goes away. Expiry alone cannot replace it: a reload
 * draws a new id, so the page that left keeps being counted next to the one
 * that replaced it. The timeout stays as the net for departures that give no
 * warning — a crash, or OBS being killed.
 */
export type ByeMessage = { v: typeof PROTOCOL_VERSION; t: 'bye'; id: string };
export type ConfigMessage = { v: typeof PROTOCOL_VERSION; t: 'config'; config: ResolvedConfig };
export type FrameMessage = { v: typeof PROTOCOL_VERSION; t: 'frame'; k: FrameKey[] };

export type OverlayMessage =
  | HelloMessage
  | BeatMessage
  | ByeMessage
  | ConfigMessage
  | FrameMessage;

const KNOWN_TYPES = ['hello', 'beat', 'bye', 'config', 'frame'] as const;
/** The three the overlay sends about itself, all keyed by its id. */
const PRESENCE_TYPES: readonly string[] = ['hello', 'beat', 'bye'];

export function envelope(message: OverlayMessage): { heOverlay: OverlayMessage } {
  return { heOverlay: message };
}

function isFrameKey(value: unknown): value is FrameKey {
  if (!Array.isArray(value) || value.length !== 3) return false;
  const [id, travel, active] = value;
  // Finite, not merely numeric. NaN survives every clamp downstream — it is
  // neither greater nor smaller than anything — and lands in the SVG as
  // height="NaN", which silently removes the key from the render.
  return Number.isFinite(id) && Number.isFinite(travel) && (active === 0 || active === 1);
}

/**
 * Returns the message when it matches our version and shape, `null` otherwise.
 * Each page then silently ignores the types that do not concern it (spec §6).
 *
 * The shape is checked, not assumed: this is a trust boundary. Any client
 * connected to the same obs-websocket can emit a CustomEvent under our key, and
 * a frame whose `k` is missing would blow up the overlay's next render — a
 * failure nobody watching the configuration screen would ever notice.
 */
export function parseMessage(payload: unknown): OverlayMessage | null {
  if (typeof payload !== 'object' || payload === null) return null;

  const inner = (payload as { heOverlay?: unknown }).heOverlay;
  if (typeof inner !== 'object' || inner === null) return null;

  const { v, t } = inner as { v?: unknown; t?: unknown };
  if (v !== PROTOCOL_VERSION) return null;
  if (typeof t !== 'string' || !KNOWN_TYPES.includes(t as (typeof KNOWN_TYPES)[number])) return null;

  if (t === 'frame') {
    const { k } = inner as { k?: unknown };
    if (!Array.isArray(k) || !k.every(isFrameKey)) return null;
  }

  if (t === 'config') {
    const { config } = inner as { config?: unknown };
    // Fully checked, not merely "an object". The plan argued both sides are
    // built from the same repository — true of the sender we intend, and
    // nothing to do with the channel. `buildScene` reads `keys.filter` and
    // `style.radius` without a fallback, so a config shaped wrong takes the
    // overlay down for the rest of the stream.
    if (!isResolvedConfig(config)) return null;
  }

  if (PRESENCE_TYPES.includes(t)) {
    const { id } = inner as { id?: unknown };
    // An unusable id would register as an overlay keyed `undefined`: one
    // phantom listener the capture page counts forever, and the status bar
    // saying someone is watching when nobody is. On a bye it cuts the other
    // way — that is the message which removes a listener.
    if (typeof id !== 'string' || id === '') return null;
  }

  return inner as OverlayMessage;
}
